### PR TITLE
fix wrong action buttons padding in data picker

### LINKED ISSUE #281: Fix wrong action buttons padding in DatePickerDialog

### PR DESCRIPTION
**Pull request by fatmahgazy**
https://github.com/user-attachments/assets/450d56a9-5fff-47e5-a305-d1a6c86ee3e5

### CODE REVIEW

**Review by MahmoodTarek — APPROVED** [review]
Great work , Fatma

**Review by fatimafaisalghazi — APPROVED** [review]

File: app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt [hunk 1]
```diff
@@ -35,10 +37,13 @@ fun DialogActionButtons(
         )
         Spacer(modifier = Modifier.weight(1f))
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt:39]: there is a space between spacer and text button

File: app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt [hunk 2]
```diff
@@ -35,10 +37,13 @@ fun DialogActionButtons(
...
         TextButton(
+            modifier = Modifier.widthIn(min = 74.dp),
             label = stringResource(id = R.string.cancel_text),
             onClick = onDismiss
         )
         TextButton(
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt:48]: and here

File: app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt [hunk 3]
```diff
@@ -35,10 +37,13 @@ fun DialogActionButtons(
...
+            modifier = Modifier.padding(start = 8.dp)
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt]: you can put the padding in a new line to be more readable

File: app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt [hunk 4]
```diff
@@ -35,10 +37,13 @@ fun DialogActionButtons(
         )
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt:37]: there is a space between spacer and text button

File: app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt [hunk 5]
```diff
@@ -24,8 +26,8 @@ fun DialogActionButtons(
     Row(
             modifier = Modifier
                 .fillMaxWidth()
-                .padding(end = 2.dp),
-    horizontalArrangement = Arrangement.SpaceBetween
+                .padding(start = 12.dp, end = 2.dp),
+             horizontalArrangement = Arrangement.SpaceBetween
     ) {
         TextButton(
             label = stringResource(id = R.string.clear_text),
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt:33]: you can if you want put the content of the onclick at the same line

**Review by Arzo-zi — DISMISSED** [review]

**Review by Malak187 — APPROVED** [review]
