### PR TITLE
Fix/ refactor onboarding screen

### LINKED ISSUE #260: Set isFirstLaunch only when user skips or completes on boarding

### PR DESCRIPTION
**Pull request by abdulazizacc**
### Now as you can see the onboarding process works as it supposed to be!

https://youtube.com/shorts/KILDBDYBrP8

### CODE REVIEW

**Review by MuhammedEdrees — APPROVED** [review]
Great job, Aziz 👏 Keep going!

File: app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+class OnboardingViewModel(
+    private val appConfigurationService: AppConfigurationService
+) : OnboardingInteractionListener,
+    BaseViewModel<OnboardingState, OnboardingScreenEffect>(OnboardingState()) {
+
+    private fun completeOnboarding() {
+        tryToExecute(
+            function = { 
+                appConfigurationService.setTheme(false)
```
Comment (omer1998) [inline app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingViewModel.kt]: I wonder why you would set the theme to be false after the user completes the onboarding screens
setting the onboarding complete is totally reasonable and logical

**Review by omer1998 — COMMENTED** [review]
Great work aziz

File: app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingViewModel.kt (hunk 1 above)
Comment (abdulazizacc) [reply app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingViewModel.kt]: good point catching this Omer, thank you so much for your review

**Review by omer1998 — APPROVED** [review]

**Review by Hasa9nAli — APPROVED** [review]

File: app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingScreen.kt [hunk 2]
```diff
@@ -19,29 +19,56 @@ import androidx.compose.foundation.pager.HorizontalPager
...
+    val pagerState = rememberPagerState { 3 }
+
+    LaunchedEffect(state.currentPage) {
+        pagerState.animateScrollToPage(state.currentPage)
     }
-    val scope = rememberCoroutineScope()
+
     val titleList = listOf(
         stringResource(id = R.string.title_0),
         stringResource(id = R.string.title_1),
```
Comment (ABDULLAHHG) [inline app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingScreen.kt:74]: you should put them in remeber 
all of the 3 variable
but idk i remember we did that before

Comment (abdulazizacc) [reply app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingScreen.kt:74]: why should I?
they are static values and don't depend on any state, and I already cannot call `stringResource` inside a `remember`

Comment (ABDULLAHHG) [reply app/src/main/java/com/baghdad/tudee/ui/screens/Onboarding/OnboardingScreen.kt:74]: you should put the `list` that contains `stringResource` in `remember` not the `stringResource` it self
