### PR TITLE
fix system navigation bar background color 

### LINKED ISSUE #276: fix system navigation bar background color not the same as app bottom navigation background color
https://github.com/user-attachments/assets/ce01088d-519e-4c83-abe7-212b5f0492a4

### PR DESCRIPTION
**Pull request by ABDULLAHHG**
# :information_source: PR Info
### :page_facing_up: Description

fix system navigation bar background color not the same as app bottom navigation background color

[fix_system_bar_navigation_color.webm](https://github.com/user-attachments/assets/79be2d5c-6727-4ede-a17a-2aababe5f286)

### CODE REVIEW

File: app/src/main/java/com/baghdad/tudee/ui/main/MainActivity.kt [hunk 1]
```diff
@@ -74,8 +76,9 @@ class MainActivity : ComponentActivity() {
         }
         Column(
             modifier = Modifier
-                .fillMaxSize()
+                .background(Theme.color.surfaceColor.surfaceHigh)
                 .navigationBarsPadding()
+                .fillMaxSize()
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/main/MainActivity.kt:81]: i think you should add fillMaxSize() after modifier

**Review by fatmahgazy — APPROVED** [review]
good job !

**Review by MuhammedEdrees — APPROVED** [review]
Great job, Aboud 👏

**Review by Arzo-zi — APPROVED** [review]
