### PR TITLE
Fix/swiping horizontal pager in category tasks screen

### LINKED ISSUE #164: Swiping in horizontal pager in category tasks screen doesn't update selected tab and isn't working properly.

### PR DESCRIPTION
**Pull request by abdulazizacc**
Fixed the issue of task bar sequence, and also fixed the swiping part in this part of screen, so they both swipes dynamically,
and also added padding at the top 

[this.webm](https://github.com/user-attachments/assets/ff78a0ba-2ead-4b49-9a47-1437289ea516)

### CODE REVIEW

File: app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt [hunk 1]
```diff
@@ -93,15 +93,22 @@ private fun CategoryTasksScreenContent(
...
+        }
+    }
+
     val tabs = listOf(
-        Selectable(
-            TabItem("In Progress", state.inProgressTasks.size, Task.State.IN_PROGRESS),
-            isSelected = state.selectedTab == Task.State.IN_PROGRESS
-        ),
         Selectable(
             TabItem("To Do", state.todoTasks.size, Task.State.TODO),
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt]: try to use string resource for consistency

File: app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt [hunk 2]
```diff
@@ -93,15 +93,22 @@ private fun CategoryTasksScreenContent(
...
             isSelected = state.selectedTab == Task.State.TODO
         ),
+        Selectable(
+            TabItem("In Progress", state.inProgressTasks.size, Task.State.IN_PROGRESS),
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt]: try to use string resource here too

File: app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt [hunk 3]
```diff
@@ -141,8 +152,8 @@ private fun CategoryTasksScreenContent(
             modifier = Modifier.weight(1f)
         ) { page ->
             val tasks = when (Task.State.entries[page]) {
-                Task.State.TODO -> state.todoTasks
                 Task.State.IN_PROGRESS -> state.inProgressTasks
+                Task.State.TODO -> state.todoTasks
                 Task.State.DONE -> state.doneTasks
             }
             if (tasks.isEmpty()) {
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt:167]: why if scope is empty ?

File: app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt (hunk 2 above)
Comment (abdulazizacc) [reply app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt]: I will, thanks for your review Fatma!

File: app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt (hunk 3 above)
Comment (abdulazizacc) [reply app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt:167]: so we can show this screen when we have no tasks

Screenshot_20250623_010729

**Review by MuhammedEdrees — APPROVED** [review]
Great job, Aziz 👏

**Review by MahmoodTarek — APPROVED** [review]
Great work , Zezo

**Review by fatmahgazy — APPROVED** [review]
