### PR TITLE
Fix/set status bar icon color based on screen background not device theme

### LINKED ISSUE #126: Status bar colors should be depend on app theme and not device theme

### PR DESCRIPTION
**Pull request by MahmoodTarek**
Issue #126 
Status bar colors should be depend on app theme and not device theme

IMG_20250622_070159
IMG_20250622_070227
IMG_20250622_070258
IMG_20250622_070315
IMG_20250622_070245
IMG_20250622_070329

- moved status bar icon color logic into TudeeTheme
- icons now change color based on app theme (dark/light)
- system theme no longer controls status bar appearance

### CODE REVIEW

**Review by MuhammedEdrees — APPROVED** [review]
Well done👏

**Review by fatmahgazy — APPROVED** [review]
good job Mahmoud!

File: app/src/main/java/com/baghdad/tudee/ui/utils/StatusBarTitleTheme.kt [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+import android.app.Activity
+import androidx.compose.runtime.Composable
+import androidx.compose.runtime.SideEffect
+import androidx.compose.ui.platform.LocalView
+import androidx.core.view.WindowInsetsControllerCompat
+
+@Composable
+fun StatusBarTitleTheme(isDark: Boolean) {
+    val view = LocalView.current
+    val window = (view.context as Activity).window
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/utils/StatusBarTitleTheme.kt:12]: Just a question:What does this part represent?

File: app/src/main/java/com/baghdad/tudee/ui/utils/StatusBarTitleTheme.kt [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+
+    SideEffect {
+        WindowInsetsControllerCompat(window!!, view).isAppearanceLightStatusBars = !isDark
+    }
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/utils/StatusBarTitleTheme.kt:16]: Why are you using (!!)?

File: app/src/main/java/com/baghdad/tudee/ui/utils/StatusBarTitleTheme.kt (hunk 1 above)
Comment (MahmoodTarek) [reply app/src/main/java/com/baghdad/tudee/ui/utils/StatusBarTitleTheme.kt:12]: it's composable function take parameter isDark 
then get the current view and  From the current View's context, it casts it to an Activity and gets the window object.

**Review by Arzo-zi — APPROVED** [review]
learn new things from you, great job
