### PR TITLE
 Fix/correctly move task to done state from bottom sheet

### LINKED ISSUE #179: "Move to Done" action in Bottom Sheet does not update task state from In Progress to Done
When tapping the "Move to Done" button in the task bottom sheet, the task remains in the In Progress list and is not moved to the Done section as expected.

### PR DESCRIPTION
**Pull request by MahmoodTarek**
Fixed an issue where tapping "Move to Done" in the bottom sheet didn’t update the task state due to incorrect use of getTasksByCategory. Now the task is retrieved from in-memory state and properly updated.

done

### CODE REVIEW

**Review by fatmahgazy — COMMENTED** [review]
good job

File: app/src/main/java/com/baghdad/tudee/viewModel/homescreenViewModel/HomeScreenViewModel.kt [hunk 1]
```diff
@@ -176,22 +176,24 @@ class HomeScreenViewModel(
...
-                                )
-                            }
-                        } ?: run {
-                            _state.update { it.copy(errorMessage = "Task not found") }
-                        }
+                val task = _state.value.inProgressTasks.find { it.id == taskId }
+                    ?: _state.value.todoTasks.find { it.id == taskId }
+
+                if (task != null) {
+                    val updatedTask = task.copy(state = Task.State.DONE)
```
Comment (abdulazizacc) [inline app/src/main/java/com/baghdad/tudee/viewModel/homescreenViewModel/HomeScreenViewModel.kt:182]: why when it is null that mean it has DONE state? I did not understand that

**Review by abdulazizacc — APPROVED** [review]

**Review by Arzo-zi — APPROVED** [review]
Keep going

File: app/src/main/java/com/baghdad/tudee/viewModel/homescreenViewModel/HomeScreenViewModel.kt [hunk 2]
```diff
@@ -176,22 +176,24 @@ class HomeScreenViewModel(
...
+
+                    _state.update { currentState ->
+                        currentState.copy(
+                            inProgressTasks = currentState.inProgressTasks - task,
+                            todoTasks = currentState.todoTasks - task,
+                            doneTasks = currentState.doneTasks + updatedTask,
+                        )
                     }
+                } else {
+                    _state.update { it.copy(errorMessage = "Task not found") }
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/viewModel/homescreenViewModel/HomeScreenViewModel.kt:193]: try to use string resource

File: app/src/main/java/com/baghdad/tudee/viewModel/homescreenViewModel/HomeScreenViewModel.kt [hunk 3]
```diff
@@ -206,7 +208,7 @@ class HomeScreenViewModel(
             try {
                 _state.value.inProgressTasks.find { it.id == taskId }?.let { task ->
                     taskService.editTask(
-                        task.copy(state = Task.State.DONE)
+                        task.copy(state = Task.State.TODO)
                     )
                 } ?: run {
                     _state.update { it.copy(errorMessage = "Task not found") }
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/viewModel/homescreenViewModel/HomeScreenViewModel.kt:213]: here too , replace string  by use string resource

**Review by MuhammedEdrees — APPROVED** [review]
Keep going 👏
