### PR TITLE
Fix/tasks screen bugs

### LINKED ISSUE #149: Fix: Tasks screen bugs
- [x] This component should be clickable and not just the arrow.

Image

- [x] Add Horizontal pager for scrolling between lists support 

- [ ] Fix this padding.

Image

- [ ] DeleteTaskBottomSheet should open when swiping on task.
- [ ] Fix scroll behaviour( Cannot scroll vertically when pointing on TaskItem).
- [ ] Selected date should be added as initial date when clicking add task.

### PR DESCRIPTION
**Pull request by MuhammedEdrees**
### PR Content
- Fixed a bug where clicking on month name doesn't show date picker.
- Added horizontal pager for better user experience.

### CODE REVIEW

**Review by MahmoodTarek — APPROVED** [review]
Great work, Edrees thanks a lot man

**Review by Arzo-zi — APPROVED** [review]

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/TasksScreen.kt [hunk 1]
```diff
@@ -93,17 +100,19 @@ fun TasksScreenContent(
...
+                onTabSelected = {
+                    scope.launch {
+                        pagerState.animateScrollToPage(it.ordinal)
+                    }
+                },
+                selectedTab = uiState.selectedTab
+            )
+            TasksHorizontalPager(
+                uiState = uiState,
+                onTaskClick = {},
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/TasksScreen.kt]: why  onTaskClick is empty?

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt [hunk 2]
```diff
@@ -16,42 +16,41 @@ import com.baghdad.tudee.ui.shared.Selectable
 
 @Composable
 fun StatusTabs(
-    tasksInteractionListener: TasksInteractionListener,
+    onTabSelected: (Task.State) -> Unit,
     uiState: TasksUiState,
+    selectedTab: Task.State,
     modifier: Modifier = Modifier
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt:22]: just a Q : is better is add modifier at the first or like you do here?

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt [hunk 3]
```diff
@@ -16,42 +16,41 @@ import com.baghdad.tudee.ui.shared.Selectable
...
 ) {
     val context = LocalContext.current
     Row(
         modifier = modifier
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt:26]: why you add this modifier here is it necessary?

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/TasksHorizontalPager.kt [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+    onTaskClick: (Task) -> Unit,
+    onDeleteTask: (Task) -> Unit,
+    pagerState: PagerState,
+    modifier: Modifier = Modifier,
+) {
+    HorizontalPager(
+        state = pagerState,
+    ) { currentPage ->
+        when(currentPage){
+            0 -> {
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/TasksHorizontalPager.kt]: i think is better not use hard coded here like numbers

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt [hunk 5]
```diff
@@ -16,42 +16,41 @@ import com.baghdad.tudee.ui.shared.Selectable
 
 @Composable
 fun StatusTabs(
-    tasksInteractionListener: TasksInteractionListener,
+    onTabSelected: (Task.State) -> Unit,
     uiState: TasksUiState,
+    selectedTab: Task.State,
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt:21]: can you explain what is diffrenet between onTabSelected and selectedTab , and can we change one of them to maningful name?

**Review by fatmahgazy — APPROVED** [review]
good job Muhammed!

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt (hunk 3 above)
Comment (Arzo-zi) [reply app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt:26]: recommended pattern: any function should have modifier if you will modify any thing inside this function it will be easier to modify it  from outside and to achieve Open/Closed Principle

Comment (MuhammedEdrees) [reply app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt:26]: @Arzo-zi Exactly

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt (hunk 2 above)
Comment (MuhammedEdrees) [reply app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt:22]: It's recommended that modifier should be the first optional modifier.

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt (hunk 5 above)
Comment (MuhammedEdrees) [reply app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/StatusTabs.kt:21]: onTabSelected is a higher order function that is performed when user clicks on a new tab. selectedTab is the actual selected tab from ui state. I think the names are pretty meaningful.

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/TasksHorizontalPager.kt (hunk 4 above)
Comment (MuhammedEdrees) [reply app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/TasksHorizontalPager.kt]: I agree.
