### PR TITLE
Fix/update category image and task count display 

### LINKED ISSUE #170: The icon of task card in home screen is not as the same one we have selected in add task bottom sheet and the count of tasks is proven
For context it does get updated when we click on it and get to details bottom sheet, but in home screen it does not get displayed correctly

### PR DESCRIPTION
**Pull request by MahmoodTarek**
Fixed an issue where the task category image did not update correctly when task data changed. Also fixed the task count display to ensure it reflects the latest number of tasks in each section dynamically.

Extracted a reusable TaskSection composable to handle rendering of task groups (To-Do, In Progress, Done).
Removed repeated LazyRow and CategoryTaskCard logic across the home screen.
Improved maintainability and UI consistency by centralizing task rendering logic.

task

### CODE REVIEW

File: app/src/main/java/com/baghdad/tudee/ui/composable/TaskSection.kt [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+        TextHeadTaskSection(
+            name = title,
+            numberOfItem = tasks.size,
+            modifier = Modifier
+                .padding(
+                    start = 16.dp,
+                    end = 16.dp,
+                    bottom = 8.dp
+                )
+        ) {}
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/composable/TaskSection.kt:41]: delete this curl braces

File: app/src/main/java/com/baghdad/tudee/ui/screens/homeScreen/HomeScreen.kt [hunk 2]
```diff
@@ -523,69 +382,70 @@ fun OverviewCard(
...
-                        },
-                        tint = Theme.color.textColor.onPrimary,
-                        modifier = Modifier.size(24.dp)
+                .background(Color.Transparent, shape = RoundedCornerShape(20.dp))
+        ) {
+            Box(
+                modifier
+                    .size(40.dp)
+                    .background(
+                        color = Color(0x3DFFFFFF),
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/screens/homeScreen/HomeScreen.kt:401]: try to use desgin system

**Review by fatmahgazy — APPROVED** [review]
well done!

File: app/src/main/java/com/baghdad/tudee/ui/screens/homeScreen/HomeScreen.kt [hunk 3]
```diff
@@ -226,241 +221,105 @@ fun HomeScreenContent(modifier: Modifier = Modifier) {
...
-                                                )
                                             }
-                                        }
-                                    }
+                                        ),
+                                        contentDescription = when (state.sliderState) {
+                                            SliderState.STAY_WORKING -> "Happy Robot"
+                                            SliderState.TADOO -> "Cute Robot"
+                                            SliderState.ZERO_PROGRESS -> "Angry Robot"
+                                            SliderState.NOTHING_IN_YOUR_LIST -> "Happy Robot"
```
Comment (abdulazizacc) [inline app/src/main/java/com/baghdad/tudee/ui/screens/homeScreen/HomeScreen.kt:238]: let's use string resources here

**Review by abdulazizacc — APPROVED** [review]
well done man

**Review by MuhammedEdrees — APPROVED** [review]
Well done, Mahmood 👏

File: app/src/main/java/com/baghdad/tudee/ui/screens/homeScreen/HomeScreen.kt (hunk 3 above)
Comment (MahmoodTarek) [reply app/src/main/java/com/baghdad/tudee/ui/screens/homeScreen/HomeScreen.kt:238]: this thing not related with my PR code

**Review by MuhammedEdrees — APPROVED** [review]
Great effort bro 👏
