### PR TITLE
Fix/task screen header arrow direction and header background

### LINKED ISSUE #203: The background for not selected days in day chip and count number for the tabs does not appear in tasks screen
In tasks screen and selected tabs the background color of it does not appear, it just takes the same color of the whole screen color  background,
here are some images that show what I'm talking about:

how it supposed to be:
Image

how it is going on in our application:
Image

### LINKED ISSUE #210: fix arrow direction at arabic in the task screen
Image

### LINKED ISSUE #215: days name in task screen should be change to arabic when change the language
Image

### PR DESCRIPTION
**Pull request by ABDULLAHHG**
# :information_source: PR Info
### :page_facing_up: Description
1 - change background color from surface to high surface in task screen header 
2 - add horizontal spacing between each day chip 
3 - fix arrow right and left direction when change to arabic language
4 - fix days names not change to arabic when change to arabic language
5 - remove animation when text color change from black to white in day chip

https://github.com/user-attachments/assets/58bce9bb-cae8-4177-a3ce-ae82bcc392cf

this video is outdated not include point 5

### CODE REVIEW

**Review by Farah-Dev4 — APPROVED** [review]
great work !

File: app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt [hunk 1]
```diff
@@ -28,15 +28,9 @@ fun DayChip(
...
-        targetValue = if (isSelected) Theme.color.textColor.onPrimary else Theme.color.textColor.body,
-        animationSpec = tween(durationMillis = 250)
-    )
+    val dayNumberColor = if (isSelected) Theme.color.textColor.onPrimary else Theme.color.textColor.body
 
-    val dayNameColor by animateColorAsState(
-        targetValue = if (isSelected) Theme.color.textColor.onPrimaryCaption else Theme.color.textColor.hint,
-        animationSpec = tween(durationMillis = 250)
-    )
+    val dayNameColor = if (isSelected) Theme.color.textColor.onPrimaryCaption else Theme.color.textColor.hint
```
Comment (abdulazizacc) [inline app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt:34]: great job deleting the animation, now it is much more smooth

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/TasksHeader.kt [hunk 2]
```diff
@@ -103,7 +109,12 @@ fun NavigationIcon(
             painter = icon,
             contentDescription = contentDescription,
             tint = Theme.color.textColor.body,
-            modifier = Modifier.padding(8.dp)
+            modifier = Modifier
+                .padding(8.dp)
+                .graphicsLayer {
+                    scaleX = if (isRtl) -1f else 1f
```
Comment (abdulazizacc) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/TasksHeader.kt:115]: the naming does not sound clear to me

**Review by abdulazizacc — APPROVED** [review]
as usual, great job aboud

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt [hunk 3]
```diff
@@ -113,13 +116,14 @@ fun HorizontalDayChipsRow(
...
             contentPadding = PaddingValues(horizontal = 16.dp),
+            horizontalArrangement = Arrangement.spacedBy(8.dp),
             state = LazyListState(firstVisibleItemIndex = if(dates.indexOf(selectedDate) < 2) 0 else dates.indexOf(selectedDate)-2)
         ) {
             items(dates) { date ->
                 val isSelected = date == selectedDate
                 DayChip(
                     dayNumber = date.dayOfMonth.toString(),
-                    dayName = date.dayOfWeek.name.take(3),
+                    dayName = date.dayOfWeek.getDisplayName(TextStyle.SHORT, Locale.getDefault()),
```
Comment (Arzo-zi) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt:126]: Just a question : What does this part represent? : Locale.getDefault())

**Review by Arzo-zi — APPROVED** [review]

File: app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt [hunk 4]
```diff
@@ -28,15 +28,9 @@ fun DayChip(
...
```
Comment (Hasa9nAli) [inline app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt:33]: Ahmed said it should be animate color

**Review by MuhammedEdrees — APPROVED** [review]
Well done, Aboud 👏

File: app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt [hunk 5]
```diff
@@ -28,15 +28,9 @@ fun DayChip(
     onSelected: () -> Unit = { },
 ) {
 
-    val dayNumberColor by animateColorAsState(
-        targetValue = if (isSelected) Theme.color.textColor.onPrimary else Theme.color.textColor.body,
-        animationSpec = tween(durationMillis = 250)
-    )
+    val dayNumberColor = if (isSelected) Theme.color.textColor.onPrimary else Theme.color.textColor.body
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt:31]: replace each if statement into AnimateVisability

File: app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt (hunk 4 above)
Comment (ABDULLAHHG) [reply app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt:33]: not everything should be animated its looks better without animated

File: app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt (hunk 5 above)
Comment (ABDULLAHHG) [reply app/src/main/java/com/baghdad/tudee/ui/composable/DayChip.kt:31]: not everything should be animated its looks better without animated
