### PR TITLE
Fix/DeleteTaskBottomSheet in tasks screen doesn't open

### LINKED ISSUE #160: DeleteTaskBottomSheet in tasks screen doesn't open when swiping tasks

### PR DESCRIPTION
**Pull request by MahmoodTarek**
[Uploading delete sheet.webm…]()

### CODE REVIEW

**Review by MuhammedEdrees — COMMENTED** [review]
Great work, Mahmoud. Just a small suggestion. I think the task should swipe back to normal when bottom sheet is opened. That way, when user clicks cancel and go back to tasks list it doesn't appear. Check video below and let me know what do you think.

https://github.com/user-attachments/assets/9cee31a4-cf4d-4cd8-a006-f859fcabc616

File: app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt [hunk 1]
```diff
@@ -40,25 +24,19 @@ fun DeleteTaskBottomSheet(
 
 @Composable
 fun ShowDeleteTaskSheet(
+    isVisible: Boolean,
     onDeleteConfirmed: () -> Unit = {},
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt:28]: I don't think the curly braces are necessary here

File: app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt [hunk 2]
```diff
@@ -40,25 +24,19 @@ fun DeleteTaskBottomSheet(
...
     onCancelConfirmed: () -> Unit = {},
```
Comment (fatmahgazy) [inline app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt:29]: and here too , i think is just a prameter you don't need them

**Review by fatmahgazy — APPROVED** [review]
good job Mahmoud!

**Review by Arzo-zi — APPROVED** [review]
Keep going

File: app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt (hunk 1 above)
Comment (MahmoodTarek) [reply app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt:28]: thanks Fatma about your replay but They are actually necessary here if we want to make these callbacks optional.

File: app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt (hunk 2 above)
Comment (MahmoodTarek) [reply app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt:29]: the same in here

**Review by MuhammedEdrees — APPROVED** [review]
Well done 👏

File: app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt (hunk 1 above)
Comment (Hasa9nAli) [reply app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt:28]: when we delete some thing you need the ID of this something

**Comment by fatimafaisalghazi** [comment]
great work , resolve the conflicts and merge ur work

**Review by Hasa9nAli — APPROVED** [review]
Great Work, Resolve conflict and merge it
