### PR TITLE
Fix/#319 fix theme switch button 

### LINKED ISSUE #319: Issue the whole day night switch should be clikcable
https://github.com/user-attachments/assets/d7ce7636-7bfd-4722-b9f7-684b4a33f39a

### PR DESCRIPTION
**Pull request by omer1998**
#319 
## what has been done
- fix the theme switch button to be able to able to capture user interaction over all button not only on the circle of the button

### CODE REVIEW

**Review by MuhammedEdrees — APPROVED** [review]
Well done, @omer1998 👏

File: app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/DayNightSwitch.kt [hunk 1]
```diff
@@ -79,7 +82,6 @@ fun DayNightSwitch(
                             .size(32.dp)
                             .align(Alignment.CenterStart)
                             .clip(CircleShape)
-                            .noRippleClickable(onClick = onClick)
                     )
                 }
             }
```
Comment (ABDULLAHHG) [inline app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/DayNightSwitch.kt:87]: there is 2 .noRippleClickable you delete 1,
and still there is one you have to delete it

**Review by ABDULLAHHG — APPROVED** [review]

**Review by abdulazizacc — APPROVED** [review]
Fine job omer
