### PR TITLE
Fix/#307 localize month year tasks screen

### LINKED ISSUE #307: Month and year are not localized in tasks screen
Image

### PR DESCRIPTION
**Pull request by Arzo-zi**
PR Summary:

- Localized the task header: it now displays in Arabic when the device language is set to Arabic.
- Enhanced month display for English: month names are now trimmed to the first three characters for a concise and   consistent appearance.

### CODE REVIEW

**Comment by Arzo-zi** [comment]
Screenshot 2025-07-02 at 12 09 54 am
Screenshot 2025-07-02 at 12 08 34 am

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt [hunk 1]
```diff
@@ -50,11 +50,17 @@ fun HorizontalDayChipsSetup(
...
 
     TasksHeader(
-        month = uiState.currentMonth.toString().take(3),
-        year = uiState.currentYear.toString(),
+        month =monthStr,
+        year = if ( Locale.getDefault().displayLanguage== "English") {//.layoutDirection == LayoutDirection.Rtl
+            yearStr.take(3)
+        } else {
+            yearStr
+        },
```
Comment (Hasa9nAli) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt]: i think this is not clear name

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt [hunk 2]
```diff
@@ -50,11 +50,17 @@ fun HorizontalDayChipsSetup(
 
     val dates: List<LocalDate> = uiState.monthDates
 
-
+    val (_, yearStr, monthStr) = getLocalizedDateParts(
+        LocalDate(uiState.currentYear, uiState.currentMonth, 1)
+    )
```
Comment (MuhammedEdrees) [inline app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt]: I think the order is reversed here, month name should be before year similar to design
image

**Review by MuhammedEdrees — CHANGES_REQUESTED** [review]
Well done, Zinah. Just a small change and you're good to go.

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt (hunk 2 above)
Comment (Arzo-zi) [reply app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt]: good note i will fix it

File: app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt (hunk 1 above)
Comment (Arzo-zi) [reply app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/HorizontalDayChipsSetup.kt]: i will try to think in another name

**Review by MuhammedEdrees — APPROVED** [review]
Great job 👏

**Review by ABDULLAHHG — APPROVED** [review]

**Review by abdulazizacc — APPROVED** [review]
fine work
